import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';

export const generateAuditReport = (decision: any, userEmail: string = 'System') => {
  const doc: any = new jsPDF();
  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();
  const primaryColor: [number, number, number] = [15, 23, 42]; // Slate 900
  const accentColor: [number, number, number] = [59, 130, 246]; // Blue 500

  const formatReportDate = () => {
    return new Date().toLocaleString('en-IN', {
      day: 'numeric',
      month: 'long',
      year: 'numeric',
      hour: '2-digit',
      minute: '2-digit',
      timeZone: 'Asia/Kolkata',
      timeZoneName: 'short'
    });
  };

  const formatDecisionDate = (dateString: string) => {
    return new Date(dateString).toLocaleString('en-IN', {
      day: 'numeric',
      month: 'long',
      year: 'numeric',
      hour: '2-digit',
      minute: '2-digit',
      timeZone: 'Asia/Kolkata',
      timeZoneName: 'short'
    });
  };

  const addHeaderFooter = (pageNum: number, title: string) => {
    // Top Bar
    doc.setFillColor(primaryColor[0], primaryColor[1], primaryColor[2]);
    doc.rect(0, 0, pageWidth, 25, 'F');
    doc.setTextColor(255, 255, 255);
    doc.setFontSize(16);
    doc.setFont("helvetica", "bold");
    doc.text("NEUROCLOAK", 14, 16);
    doc.setFontSize(10);
    doc.setFont("helvetica", "normal");
    doc.text("Cognitive Audit", pageWidth - 14, 16, { align: 'right' });

    // Page Title
    doc.setTextColor(primaryColor[0], primaryColor[1], primaryColor[2]);
    doc.setFontSize(22);
    doc.setFont("helvetica", "bold");
    doc.text(title, 14, 45);

    // Footer
    doc.setDrawColor(220);
    doc.line(14, pageHeight - 15, pageWidth - 14, pageHeight - 15);
    doc.setFontSize(9);
    doc.setTextColor(150);
    doc.text(formatReportDate(), 14, pageHeight - 8);
    doc.text(`Page ${pageNum} of 5`, pageWidth - 14, pageHeight - 8, { align: 'right' });
  };

  // --- PAGE 1: Cover Page ---
  // Large full-page aesthetic design
  doc.setFillColor(primaryColor[0], primaryColor[1], primaryColor[2]);
  doc.rect(0, 0, pageWidth, pageHeight, 'F');
  
  // Title
  doc.setTextColor(255, 255, 255);
  doc.setFontSize(40);
  doc.setFont("helvetica", "bold");
  doc.text("NEUROCLOAK", pageWidth / 2, 80, { align: 'center' });
  
  doc.setTextColor(accentColor[0], accentColor[1], accentColor[2]);
  doc.setFontSize(18);
  doc.setFont("helvetica", "bold");
  doc.text("COGNITIVE DIGITAL TWIN", pageWidth / 2, 95, { align: 'center' });
  doc.setTextColor(200);
  doc.setFont("helvetica", "normal");
  doc.text("AUDIT REPORT", pageWidth / 2, 105, { align: 'center' });
  
  // White Box for Details
  doc.setFillColor(255, 255, 255);
  doc.roundedRect(pageWidth / 2 - 90, 125, 180, 120, 5, 5, 'F');

  const leftX = pageWidth / 2 - 80;
  const rightX = pageWidth / 2 + 20;

  const fields = [
    { label: "DECISION ID", value: decision.id },
    { label: "AI SYSTEM", value: decision.aiSystem?.name || 'Unknown' },
    { label: "DOMAIN", value: decision.aiSystem?.domain ? (decision.aiSystem.domain.charAt(0).toUpperCase() + decision.aiSystem.domain.slice(1)) : 'Unknown' },
    { label: "DECISION TIME", value: formatDecisionDate(decision.createdAt) },
    { label: "CONFIDENCE", value: (decision.confidenceScore * 100).toFixed(1) + "%" },
    { label: "GENERATED BY", value: userEmail },
    { label: "GENERATED ON", value: formatReportDate() }
  ];

  let startY = 140;
  fields.forEach(field => {
    doc.setTextColor(100);
    doc.setFont("helvetica", "normal");
    doc.setFontSize(9);
    doc.text(field.label, leftX, startY);
    
    doc.setTextColor(primaryColor[0], primaryColor[1], primaryColor[2]);
    doc.setFont("helvetica", "bold");
    doc.text(field.value, leftX, startY + 6);
    
    startY += 15;
  });

  // Status Box inside the white card
  const statusColors: any = {
    APPROVED: [22, 163, 74],
    FLAGGED: [234, 179, 8],
    BLOCKED: [239, 68, 68]
  };
  const color = statusColors[decision.status] || [100, 100, 100];
  doc.setFillColor(color[0], color[1], color[2]);
  doc.roundedRect(rightX, 140, 60, 15, 2, 2, 'F');
  doc.setTextColor(255, 255, 255);
  doc.setFontSize(10);
  doc.setFont("helvetica", "bold");
  doc.text(decision.status, rightX + 30, 150, { align: 'center' });
  
  doc.setTextColor(100);
  doc.setFont("helvetica", "normal");
  doc.text("FINAL RESOLUTION", rightX + 30, 136, { align: 'center' });

  // Domain-specific description
  let domainDescription = "AI system decision analysis — NeuroCloak cognitive audit";
  if (decision.aiSystem?.domain === 'healthcare') domainDescription = "Clinical decision support analysis — MediScan AI cognitive audit";
  if (decision.aiSystem?.domain === 'finance') domainDescription = "Financial risk assessment analysis — FinGuard AI cognitive audit";
  if (decision.aiSystem?.domain === 'defense') domainDescription = "Autonomous defense evaluation — SentryMind AI cognitive audit";

  doc.setTextColor(150);
  doc.setFontSize(9);
  doc.text(domainDescription, rightX + 30, 165, { align: 'center', maxWidth: 60 });

  // --- PAGE 2: Executive Summary ---
  doc.addPage();
  addHeaderFooter(2, "CDT Performance Metrics");

  const selfRepairValue =
    decision.selfRepairEfficiency !== null &&
    decision.selfRepairEfficiency !== undefined
      ? (decision.selfRepairEfficiency * 100).toFixed(1) + "%"
      : "N/A — No bias detected";

  autoTable(doc, {
    startY: 55,
    head: [['Metric', 'Score', 'Meaning']],
    body: [
      ['Cognitive Consistency', (decision.cognitiveConsistency * 100).toFixed(1) + '%', 'How accurately the CDT mirrors AI reasoning'],
      ['Transparency Index', (decision.transparencyIndex * 100).toFixed(1) + '%', '% of reasoning steps that are human-readable'],
      ['Ethical Compliance', (decision.ethicalComplianceRate * 100).toFixed(1) + '%', '% of governance rules satisfied'],
      ['Adaptation Speed', Math.round(decision.adaptationSpeed) + 'ms', 'Time to restabilize after environment change'],
      ['Self-Repair Efficiency', selfRepairValue, '% of detected bias patterns that were auto-corrected by the metacognitive monitor']
    ],
    theme: 'grid',
    headStyles: { fillColor: primaryColor, textColor: 255, fontStyle: 'bold' },
    bodyStyles: { textColor: 50 },
    alternateRowStyles: { fillColor: [248, 250, 252] },
    columnStyles: { 1: { fontStyle: 'bold', textColor: accentColor } }
  });

  // --- PAGE 3: Reasoning Trace ---
  doc.addPage();
  addHeaderFooter(3, "Cognitive Reasoning Audit Trail");

  const stepsList = [...(decision.reasoningTrace || [])].sort((a: any, b: any) => a.stepNumber - b.stepNumber);
  const traceBody = stepsList.map((s: any) => [
    s.stepNumber,
    s.layer,
    s.description,
    (s.confidence * 100).toFixed(1) + '%',
    s.durationMs + 'ms',
    s.isInterpretable ? 'Yes' : 'No'
  ]);

  autoTable(doc, {
    startY: 55,
    head: [['Step', 'Layer', 'Description', 'Confidence', 'Duration', 'Interpretable']],
    body: traceBody,
    theme: 'grid',
    headStyles: { fillColor: primaryColor, textColor: 255, fontStyle: 'bold' },
    bodyStyles: { textColor: 50 },
    alternateRowStyles: { fillColor: [248, 250, 252] },
    columnStyles: { 
      0: { fontStyle: 'bold', cellWidth: 15 },
      2: { cellWidth: 80 } 
    }
  });

  // --- PAGE 4: Ethics and Governance ---
  doc.addPage();
  addHeaderFooter(4, "Governance Compliance Checks");

  const checksBody = decision.ethicsChecks?.map((c: any) => [
    c.rule?.name || 'Unknown Rule',
    c.rule?.category || 'General',
    c.passed ? 'PASS' : 'FAIL',
    c.reason
  ]) || [];

  autoTable(doc, {
    startY: 55,
    head: [['Rule Name', 'Category', 'Result', 'Reason']],
    body: checksBody,
    theme: 'grid',
    headStyles: { fillColor: primaryColor, textColor: 255, fontStyle: 'bold' },
    bodyStyles: { textColor: 50 },
    alternateRowStyles: { fillColor: [248, 250, 252] },
    didParseCell: function(data) {
      if (data.section === 'body' && data.column.index === 2) {
        data.cell.styles.fontStyle = 'bold';
        if (data.cell.raw === 'PASS') data.cell.styles.textColor = [22, 163, 74];
        if (data.cell.raw === 'FAIL') data.cell.styles.textColor = [239, 68, 68];
      }
    }
  });

  const finalY = doc.lastAutoTable?.finalY || 55;
  doc.setFont("helvetica", "bold");
  doc.setTextColor(primaryColor[0], primaryColor[1], primaryColor[2]);
  doc.setFontSize(14);
  doc.text(`Overall Compliance Rate: ${(decision.ethicalComplianceRate * 100).toFixed(1)}%`, 14, finalY + 15);

  // --- PAGE 5: Bias Analysis ---
  doc.addPage();
  addHeaderFooter(5, "Bias Detection Report");

  if (decision.biasFlags && decision.biasFlags.length > 0) {
    const biasBody = decision.biasFlags.map((b: any) => [
      b.biasType,
      b.severity,
      b.description,
      b.corrected ? 'Auto-Corrected' : 'Unresolved'
    ]);

    autoTable(doc, {
      startY: 55,
      head: [['Bias Type', 'Severity', 'Description', 'Status']],
      body: biasBody,
      theme: 'grid',
      headStyles: { fillColor: primaryColor, textColor: 255, fontStyle: 'bold' },
      bodyStyles: { textColor: 50 },
      alternateRowStyles: { fillColor: [248, 250, 252] },
      didParseCell: function(data) {
        if (data.section === 'body') {
          if (data.column.index === 1) data.cell.styles.fontStyle = 'bold'; // Severity
          if (data.column.index === 3) {
             data.cell.styles.fontStyle = 'bold';
             if (data.cell.raw === 'Auto-Corrected') data.cell.styles.textColor = [22, 163, 74];
             else data.cell.styles.textColor = [239, 68, 68];
          }
        }
      }
    });
  } else {
    doc.setFillColor(248, 250, 252);
    doc.roundedRect(14, 55, pageWidth - 28, 40, 3, 3, 'F');
    doc.setFont("helvetica", "italic");
    doc.setFontSize(12);
    doc.setTextColor(100);
    doc.text("No bias patterns detected in this decision cycle.", pageWidth / 2, 75, { align: 'center' });
  }

  doc.save(`neurocloak-audit-${decision.id.slice(0,8)}.pdf`);
};
